name: deploy to ftp

on:
  push:
    paths-ignore: 
    - '.github6/**'
jobs:
  build:

    runs-on: ubuntu-latest

    container: 
      image: debian:stable-slim

    steps:
    - name: 初始化环境
      run: |
        apt-get update
        apt-get install -y git 
        apt-get install -y git-ftp
    - name: 克隆github项目
      uses: actions/checkout@master
      with:
          fetch-depth: 2   
    - name: 开始ftp同步
      run: |        
        #替换你的ip或域名
        git config git-ftp.url "ftp://139.199.213.12/"
        #替换你的ftp账户
        git config git-ftp.user "ftp_139_199_213_12"       
        #替换你的ftp密码        
        git config git-ftp.password "RneX8bMZ5ZT6ZAFk"
        #--disable-epsv可选，因为我的服务器不支持epsv
        git ftp push --auto-init -vv --disable-epsv
